<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">LogFileService</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCnRyeSB7
DQpTdHJpbmcgZmlsZVBhdGggPSAiL29wdC9zb2Z0d2FyZWFnL0ludGVncmF0aW9uU2VydmVyL2lu
c3RhbmNlcy9kZWZhdWx0L2xvZy93cmFwcGVyXzIwMjQwMzE1LmxvZyI7IC8vIEhhcmRjb2RlZCBm
aWxlIHBhdGgNCmlmIChmaWxlUGF0aCAhPSBudWxsICYmICFmaWxlUGF0aC5pc0VtcHR5KCkpIHsN
CnRyeSB7DQpTeXN0ZW0ub3V0LnByaW50bG4oIkF0dGVtcHRpbmcgdG8gcmVhZCBmaWxlOiAiICsg
ZmlsZVBhdGgpOw0KU3RyaW5nIGZpbGVDb250ZW50ID0gcmVhZEZpbGUoZmlsZVBhdGgpOw0KU3lz
dGVtLm91dC5wcmludGxuKCJGaWxlIGNvbnRlbnQ6Iik7DQpTeXN0ZW0ub3V0LnByaW50bG4oZmls
ZUNvbnRlbnQpOw0KSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgImZpbGVDb250ZW50Iiwg
ZmlsZUNvbnRlbnQpOw0KfSBjYXRjaCAoSU9FeGNlcHRpb24gZSkgew0KU3lzdGVtLmVyci5wcmlu
dGxuKCJFcnJvciByZWFkaW5nIGZpbGU6ICIgKyBlLmdldE1lc3NhZ2UoKSk7DQplLnByaW50U3Rh
Y2tUcmFjZSgpOyAvLyBQcmludCBzdGFjayB0cmFjZSBmb3IgZGV0YWlsZWQgZXJyb3IgaW5mbw0K
dGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24obnVsbCwgIkVycm9yIHJlYWRpbmcgZmlsZTogIiAr
IGUuZ2V0TWVzc2FnZSgpLCBmaWxlUGF0aCwgZSwgbnVsbCk7DQp9DQp9IGVsc2Ugew0KU3lzdGVt
LmVyci5wcmludGxuKCJGaWxlIHBhdGggaXMgZW1wdHkgb3IgbnVsbC4iKTsNCnRocm93IG5ldyBT
ZXJ2aWNlRXhjZXB0aW9uKCJGaWxlIHBhdGggaXMgZW1wdHkgb3IgbnVsbC4iKTsNCn0NCn0gZmlu
YWxseSB7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQp9DQp9DQoNCnB1YmxpYyBzdGF0aWMg
U3RyaW5nIHJlYWRGaWxlKFN0cmluZyBmaWxlUGF0aCkgdGhyb3dzIElPRXhjZXB0aW9uIHsNClN0
cmluZ0J1aWxkZXIgY29udGVudCA9IG5ldyBTdHJpbmdCdWlsZGVyKCk7DQpGaWxlIGZpbGUgPSBu
ZXcgRmlsZShmaWxlUGF0aCk7DQoNCmlmICghZmlsZS5leGlzdHMoKSkgew0KdGhyb3cgbmV3IElP
RXhjZXB0aW9uKCJGaWxlIG5vdCBmb3VuZCBhdCBwYXRoOiAiICsgZmlsZVBhdGgpOw0KfQ0KDQp0
cnkgKEJ1ZmZlcmVkUmVhZGVyIHJlYWRlciA9IG5ldyBCdWZmZXJlZFJlYWRlcihuZXcgRmlsZVJl
YWRlcihmaWxlKSkpIHsNClN0cmluZyBsaW5lOw0Kd2hpbGUgKChsaW5lID0gcmVhZGVyLnJlYWRM
aW5lKCkpICE9IG51bGwpIHsNCmNvbnRlbnQuYXBwZW5kKGxpbmUpLmFwcGVuZCgiXG4iKTsNCn0N
Cn0NCg0KcmV0dXJuIGNvbnRlbnQudG9TdHJpbmcoKTs=</value>
</Values>
